### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BrunoBetancourt** [bitcoin-tools/nodebuilder#604]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Debian]
 - Environment [e.g. bare metal, docker]
 - Release [e.g. 1.0.0]

**Additional context**

**Comment by bitcoin-tools** [comment]
@BrunoBetancourt thanks for creating the issue. Do you have a bug to report?

**Comment by bitcoin-tools** [comment]
Closing due to no details or reply.
